services:
  bot:
    build: .
    container_name: prosta_stal_bot
    command: tail -f /dev/null
    env_file:
      - .env
    volumes:
      - ./credentials:/app/credentials:ro
      - ./downloads:/app/downloads
      - ./src:/app/src
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
