version: '3.8'

services:
  bot:
    build: .
    container_name: prostastal_collector
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - .env
    volumes:
      - ./media:/app/media
      - ./service_account.json:/app/service_account.json
