"""DTO for AI-generated product content returned by Gemini."""
from dataclasses import dataclass


@dataclass
class GeminiContentDto:
    """Structured representation of the content fields generated by Gemini AI.

    Each field corresponds to an AI-generated marketing attribute for a
    knife product, returned in bilingual format (Ukrainian / English).
    """

    product_code: str = ""
    title: str = ""
    description: str = ""
    meta_keywords: str = ""
    meta_description: str = ""
    etsy_title: str = ""
    etsy_description: str = ""
    etsy_tags: str = ""
    engraving_description: str = ""
