"""DTO for AI-generated product content returned by Gemini."""
from dataclasses import dataclass


@dataclass
class GeminiContentDto:
    """Structured representation of the content fields generated by Gemini AI.

    Each field corresponds to an AI-generated marketing attribute for a
    knife product, returned in bilingual format (Ukrainian / English).
    """

    title_ua: str = ""
    title_en: str = ""
    description_ua: str = ""
    description_en: str = ""
    meta_keywords_ua: str = ""
    meta_keywords_en: str = ""
    meta_description_ua: str = ""
    meta_description_en: str = ""
    engraving_style: str = ""
    # etsy_title: str = ""
    # etsy_description: str = ""
    # etsy_tags: str = ""
    # engraving_description: str = ""
