# Generated by Django 5.2.12 on 2026-03-07 13:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('system_prompt', models.TextField(blank=True, default='', help_text='Instruction text for Gemini AI content generation')),
                ('attribute_schema', models.JSONField(default=list, help_text='JSON array defining the dynamic bot dialog fields')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='users.organization')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'catalog_category',
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True, help_text='FK to Organization (denormalized from Users module via events)')),
                ('attributes', models.JSONField(default=dict, help_text='Collected data — validated against Category.attribute_schema')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AI_PROCESSING', 'AI Processing'), ('READY', 'Ready'), ('ERROR', 'Error')], db_index=True, default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'catalog_product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaticReferenceGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Group name, e.g. "Blade Names", "Steel Types", "Handle Materials"', max_length=128)),
                ('field_schema', models.JSONField(default=list, help_text='JSON array defining what fields each item in this group has')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_reference_groups', to='users.organization')),
            ],
            options={
                'verbose_name': 'Static Reference Group',
                'verbose_name_plural': 'Static Reference Groups',
                'db_table': 'catalog_static_reference_group',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StaticReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Technical identifier, e.g. "yakut", "D2"', max_length=128)),
                ('label', models.CharField(help_text='Display text for bot buttons, e.g. "Якутський"', max_length=255)),
                ('value', models.JSONField(blank=True, default=dict, help_text="Characteristic values matching the group's field_schema")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.staticreferencegroup')),
            ],
            options={
                'verbose_name': 'Static Reference',
                'verbose_name_plural': 'Static References',
                'db_table': 'catalog_static_reference',
                'ordering': ['label'],
                'unique_together': {('group', 'key')},
            },
        ),
    ]
