# Generated by Django 5.2.12 on 2026-03-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_staticreferencegroup_field_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticreferencegroup',
            name='field_schema',
            field=models.JSONField(blank=True, default=list, help_text='JSON array defining what fields each item in this group has', null=True),
        ),
    ]
