# Generated by Django 5.2.12 on 2026-03-07 15:39

import core.attribute_schema
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_staticreferencegroup_field_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the bot dialog (0 = first)')),
                ('key', models.CharField(help_text='Technical key, e.g. "blade_name", "steel"', max_length=128)),
                ('label', models.CharField(help_text='Display label, e.g. "Назва ножа", "Сталь"', max_length=255)),
                ('data_type', models.CharField(choices=[('str', 'str'), ('int', 'int'), ('float', 'float')], default=core.attribute_schema.DataType['STR'], max_length=16)),
                ('source_type', models.CharField(choices=[('MANUAL', 'MANUAL'), ('STATIC_DB', 'STATIC_DB'), ('AI', 'AI')], default=core.attribute_schema.SourceType['MANUAL'], max_length=16)),
                ('multi_select', models.BooleanField(default=False, help_text='Allow selecting multiple values')),
                ('auto_fill_from_value', models.BooleanField(default=False, help_text='Auto-fill item characteristics into collected data')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.category')),
                ('source_ref_group', models.ForeignKey(blank=True, help_text='StaticReferenceGroup to pull options from (for STATIC_DB)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_attributes', to='catalog.staticreferencegroup', verbose_name='Source group')),
            ],
            options={
                'verbose_name': 'Category Attribute',
                'verbose_name_plural': 'Category Attributes',
                'db_table': 'catalog_category_attribute',
                'ordering': ['order', 'pk'],
                'unique_together': {('category', 'key')},
            },
        ),
    ]
