# Generated by Django 5.2.12 on 2026-03-07 17:53

import core.attribute_schema
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_categoryattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryattribute',
            name='optional',
            field=models.BooleanField(default=False, help_text='Allow the user to skip this field'),
        ),
        migrations.AlterField(
            model_name='categoryattribute',
            name='data_type',
            field=models.CharField(choices=[('str', 'str'), ('int', 'int'), ('float', 'float'), ('bool', 'bool'), ('file', 'file'), ('file_array', 'file_array'), ('string_array', 'string_array')], default=core.attribute_schema.DataType['STR'], max_length=16),
        ),
    ]
