# Generated by Django 5.2.12 on 2026-03-13 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_category_to_productschema'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productschema',
            options={'verbose_name': 'Product Schema', 'verbose_name_plural': 'Product Schemas'},
        ),
        migrations.AlterModelOptions(
            name='productschemafield',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Product Schema Field', 'verbose_name_plural': 'Product Schema Fields'},
        ),
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.JSONField(default=dict, help_text='Collected data — validated against ProductSchema.attribute_schema'),
        ),
        migrations.AlterField(
            model_name='productschema',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_schemas', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='productschemafield',
            name='product_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='catalog.productschema'),
        ),
        migrations.AlterField(
            model_name='productschemafield',
            name='source_ref_group',
            field=models.ForeignKey(blank=True, help_text='StaticReferenceGroup to pull options from (for STATIC_DB)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_schema_fields', to='catalog.staticreferencegroup', verbose_name='Source group'),
        ),
    ]
