# Generated by Django 5.2.12 on 2026-03-07 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionDriver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True, help_text='FK to Organization (denormalized via events)')),
                ('name', models.CharField(help_text='Human-readable name, e.g. "Horoshop Production"', max_length=128)),
                ('driver_type', models.CharField(help_text='Driver class identifier, e.g. "horoshop"', max_length=64)),
                ('credentials', models.JSONField(default=dict, help_text='Platform-specific credentials (URL, email, password, API keys)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Distribution Driver',
                'verbose_name_plural': 'Distribution Drivers',
                'db_table': 'distribution_driver',
            },
        ),
        migrations.CreateModel(
            name='DistributionManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(db_index=True, help_text='FK to Product (denormalized from Catalog via events)')),
                ('manifest_config', models.JSONField(default=dict, help_text='JSON config defining field mapping, selectors, and spec mapping')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifests', to='distribution.distributiondriver')),
            ],
            options={
                'verbose_name': 'Distribution Manifest',
                'verbose_name_plural': 'Distribution Manifests',
                'db_table': 'distribution_manifest',
                'unique_together': {('driver', 'product_id')},
            },
        ),
    ]
