# Generated by Django 5.2.12 on 2026-03-08 01:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        # 1. Спочатку створюємо колонку category_id
        migrations.AddField(
            model_name='distributionmanifest',
            name='category_id',
            field=models.CharField(db_index=True, default='default_category', help_text='Identifier of the Category this manifest applies to', max_length=255),
            preserve_default=False,
        ),
        # 2. Тільки після цього застосовуємо унікальний індекс
        migrations.AlterUniqueTogether(
            name='distributionmanifest',
            unique_together={('driver', 'category_id')},
        ),
        migrations.RemoveField(
            model_name='distributionmanifest',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='distributionmanifest',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='distributionmanifest',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='distributionmanifest',
            name='status',
        ),
        migrations.CreateModel(
            name='DistributionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(db_index=True, help_text='FK to Product (denormalized from Catalog via events)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='distribution.distributiondriver')),
            ],
            options={
                'verbose_name': 'Distribution Task',
                'verbose_name_plural': 'Distribution Tasks',
                'db_table': 'distribution_task',
                'unique_together': {('driver', 'product_id')},
            },
        ),
    ]
