# Generated by Django 5.2.12 on 2026-03-08 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_alter_distributionmanifest_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoroshopManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_id', models.CharField(db_index=True, help_text='Identifier of the Category this manifest applies to', max_length=255)),
                ('event_type', models.CharField(choices=[('CREATE', 'Create Product'), ('UPDATE', 'Update Product'), ('DELETE', 'Delete Product')], default='CREATE', help_text='The product lifecycle event that triggers this script', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horoshop_manifests', to='distribution.distributiondriver')),
            ],
            options={
                'verbose_name': 'Horoshop Manifest',
                'verbose_name_plural': 'Horoshop Manifests',
                'db_table': 'distribution_horoshop_manifest',
                'unique_together': {('driver', 'category_id', 'event_type')},
            },
        ),
        migrations.CreateModel(
            name='HoroshopStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Execution order like 1, 2, 3...')),
                ('action', models.CharField(choices=[('goto', 'Go To URL'), ('click', 'Click Element'), ('fill', 'Fill Input'), ('fill_iframe', 'Fill IFrame'), ('select', 'Select Option'), ('check', 'Check or Uncheck'), ('upload', 'Upload File'), ('wait_networkidle', 'Wait for Network Idle'), ('wait_timeout', 'Wait ms')], max_length=32)),
                ('selector', models.CharField(blank=True, default='', max_length=500)),
                ('value_source', models.CharField(blank=True, default='', help_text='Example: attributes.price', max_length=255)),
                ('static_value', models.CharField(blank=True, default='', help_text='Hardcoded value', max_length=500)),
                ('url_source', models.CharField(blank=True, default='', help_text='Example: credentials.store_url', max_length=255)),
                ('static_url', models.CharField(blank=True, default='', max_length=500)),
                ('iframe_selector', models.CharField(blank=True, default='', max_length=500)),
                ('timeout_ms', models.PositiveIntegerField(blank=True, help_text='Used for wait_timeout', null=True)),
                ('force_click', models.BooleanField(default=False, help_text='Force click ignoring overlays')),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='distribution.horoshopmanifest')),
            ],
            options={
                'verbose_name': 'Horoshop Step',
                'verbose_name_plural': 'Horoshop Steps',
                'db_table': 'distribution_horoshop_step',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='DistributionManifest',
        ),
    ]
