# Generated by Django 5.2.12 on 2026-03-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_horoshopmanifest_horoshopstep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoshopstep',
            name='action',
            field=models.CharField(choices=[('goto', 'Go To URL'), ('click', 'Click Element'), ('hover', 'Hover Element'), ('fill', 'Fill Input'), ('fill_iframe', 'Fill IFrame'), ('select', 'Select Option'), ('check', 'Check or Uncheck'), ('upload', 'Upload File'), ('wait_networkidle', 'Wait for Network Idle'), ('wait_timeout', 'Wait ms'), ('fill_youtube_iframe', 'Fill Youtube Iframe')], max_length=32),
        ),
    ]
