# Generated by Django 5.2.12 on 2026-03-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0007_rozetkafeedconfig_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoshopmanifest',
            name='product_schema_id',
            field=models.CharField(db_index=True, help_text='Identifier of the ProductSchema this manifest applies to', max_length=255),
        ),
        migrations.AlterField(
            model_name='rozetkacategorymapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rozetkafeedconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rozetkafeedconfig',
            name='rozetka_description_instructions',
            field=models.TextField(blank=True, default='', help_text="Extra AI prompt instructions for generating Rozetka-compliant descriptions. E.g.: 'Generate rozetka_description without URLs, phones, emoji...'"),
        ),
        migrations.AlterField(
            model_name='rozetkafeedconfig',
            name='rozetka_name_instructions',
            field=models.TextField(blank=True, default='', help_text="Extra AI prompt instructions for generating Rozetka-compliant product names. Appended to system_prompt when generating AI content. E.g.: 'Generate rozetka_name field following Rozetka naming rules...'"),
        ),
        migrations.AlterField(
            model_name='rozetkafieldmapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
