"""Data model for a knife product."""
from dataclasses import dataclass, field


@dataclass
class ProductData:
    """Complete knife product data structure.

    Fields marked 'AI' are generated by Gemini.
    Fields marked 'Sheets' come from Google Sheets.
    """

    product_code: str = ""
    title: str = ""
    description: str = ""
    meta_keywords: str = ""
    meta_description: str = ""
    etsy_title: str = ""
    etsy_description: str = ""
    etsy_tags: str = ""

    photo_links: list[str] = field(default_factory=list)
    price: str = ""
    blade_type: str = ""
    blade_name: str = ""
    steel: str = ""
    handle_material: str = ""
    sheath_color: str = ""
    mounts: str = ""
    accessories: str = ""
    engraving_style: str = ""
    engravings_on_blade_count: str = ""
    hardness: str = ""
    weight: str = ""
    total_length: str = ""
    blade_length: str = ""
    width: str = ""
    thickness: str = ""
    etsy_materials: str = ""
